### ISSUE TITLE
What is this project's License?

### ISSUE THREAD

**Issue by orumin** [kotetuco/Rust-BareMetal-GBA-Sample#7]
Each of source code has your sign in code's head, But that's license is unknown.
If my project is reference to this code, I cannot publishing that.
Would you specify licnese for this project, which is GPL, BSDL, MIT, Apache ... etc?

**Comment by kotetuco** [comment]
@orumin (日本語ですいません)issueありがとうございます。

遅くなりましたが、ライセンス情報を追加しました。これを機に、色んな方にコードを使っていただければと思います。

今後も何かお気づきの点があればご指摘いただければと思います。ありがとうございました！
